# Generated by Django 5.0.14 on 2026-10-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizer', 'Fertilizer'), ('Spray', 'Spray'), ('Labour', 'Labour'), ('Equipment', 'Equipment'), ('Transport', 'Transport'), ('Irrigation', 'Irrigation'), ('Harvest', 'Harvest'), ('Other', 'Other')], default='Other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expenses', to='activities.activity')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crops.crop')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
