# Generated by Django 5.0.14 on 2026-10-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('SOWING', 'Sowing'), ('IRRIGATION', 'Irrigation'), ('SPRAY', 'Spray'), ('FERTILIZER', 'Fertilizer'), ('PEST_DISEASE', 'Pest/Disease'), ('WEEDING', 'Weeding'), ('HARVEST', 'Harvest'), ('OTHER', 'Other')], max_length=50)),
                ('activity_date', models.DateField()),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('person_count', models.IntegerField(default=0, help_text='Number of persons/workers used')),
                ('cost_per_person', models.DecimalField(decimal_places=2, default=0, help_text='Daily wage rate per person', max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Calculated as person_count * cost_per_person', max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, help_text='Direct item or product cost', max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Total Activity Expense', max_digits=12)),
                ('income', models.DecimalField(decimal_places=2, default=0, help_text='Revenue gained from harvest sale', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crops.crop')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
    ]
